name: gitleaks-test-manual

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual gitleaks scan'     
        required: true
        default: 'main'
      
jobs:
  gitleaks-manual:
    name: 'Gitleaks Scan manual'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    
    - name: pwd
      id: pwd
      run: pwd
    # - name: clone gitleaks repo and build 
    #   id: build
    #   run: |
    #     wget -c https://golang.org/dl/go1.17.6.linux-amd64.tar.gz
    #     sudo tar -xvzf go1.17.6.linux-amd64.tar.gz
    #     git clone https://github.com/zricethezav/gitleaks.git
    #     cd gitleaks
    #     make build

    - name: gitleaks docker scan
      id: scan
      run: |
        docker pull zricethezav/gitleaks:latest
        docker run -v /home/runner/work/cryptoscan/cryptoscan:/path zricethezav/gitleaks:latest detect --source="/path" -v
        

    # - name: scan repo
    #   id: scan
    #   run: |
    #     cd /home/runner/work/cryptoscan/cryptoscan
    #     gitleaks detect
    
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master