name: gitleaks-manual

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual gitleaks scan'     
        required: true
        default: 'main'
      

jobs:
  gitleaks-manual:
    name: 'Gitleaks Scan manual'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: pwd
        id: pwd
        run: echo "pwd"
    
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
