name: gitleaks-scheduled

on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  gitleaks-scheduled:
    name: 'Gitleaks Scan once per day'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    
    - name: pwd
      id: pwd
      run: pwd
    
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
